# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'src.core.statistics',
        'src.core.roc',
        'src.core.bland_altman',
        'src.core.passing_bablok',
        'src.core.survival',
        'src.core.meta_analysis',
        'src.core.sample_size',
        'src.core.bootstrap',
        'src.core.random_forest',
        'src.core.agreement',
        'src.core.regression',
        'src.core.diagnostic_tests',
        'src.core.outliers',
        'src.core.reference',
        'src.core.two_way_anova',
        'src.core.ancova',
        'src.core.repeated_measures',
        'src.core.cox_regression',
        'src.core.probit',
        'src.core.cmh',
        'src.core.serial_measurements',
        'src.core.plots',
        'src.core.export',
        'src.core.validation',
        'src.ui.icons',
        'src.ui.styles',
        'src.ui.main_window',
        'src.ui.data_panel',
        'src.ui.analysis_panel',
        'src.ui.graphs_panel',
        'src.ui.qc_panel',
        'scipy',
        'scipy.stats',
        'scipy.optimize',
        'numpy',
        'pandas',
        'matplotlib',
        'matplotlib.backends.backend_qtagg',
        'PyQt6',
        'openpyxl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BioStat',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BioStat',
)
