"""Textos de ayuda (descripciones y formulas) de los analisis.

Datos extraidos de analysis_panel.py para separar contenido de logica.
"""

ANALYSIS_HELP = {
    "Estadisticas descriptivas": "Proporciona un resumen numérico fundamental (media, mediana, DE, etc.). Úselo en la fase inicial del análisis para entender la distribución y calidad de los datos numéricos antes de aplicar pruebas inferenciales.",
    "t-test pareado": "Compara las medias de dos mediciones realizadas en los mismos individuos (ej. antes y después de un tratamiento). Requiere que las diferencias entre pares sigan una distribución normal.",
    "t-test independiente": "Compara las medias de dos grupos completamente distintos (ej. pacientes sanos vs enfermos). Requiere que los datos sean numéricos continuos y aproximadamente normales en cada grupo.",
    "ANOVA una via": "Compara las medias de tres o más grupos independientes para ver si hay diferencias significativas entre ellos. Úselo cuando tiene una variable categórica de múltiples niveles y una respuesta numérica continua.",
    "Correlacion de Pearson": "Mide la fuerza de la relación lineal entre dos variables continuas (ej. concentración de dos analitos). Exige que ambas variables sigan una distribución normal y su relación sea lineal.",
    "Correlacion de Spearman": "Mide la relación monótona entre dos variables utilizando sus rangos. Es la alternativa no paramétrica a Pearson, ideal cuando los datos tienen valores atípicos (outliers) o no son normales.",
    "Shapiro-Wilk": "Evalúa formalmente si un conjunto de datos sigue una distribución normal gaussiana. Es el primer paso recomendado (p < 0.05 indica no normalidad) antes de elegir entre pruebas paramétricas o no paramétricas.",
    "Curva ROC": "Evalúa el rendimiento de un biomarcador o prueba diagnóstica. Muestra el equilibrio entre sensibilidad y especificidad a distintos puntos de corte. Requiere un resultado binario (enfermo/sano) y un valor numérico.",
    "Bland-Altman": "El estándar de oro para comparar dos métodos de medición clínica (ej. un analizador nuevo vs el de referencia). Evalúa si existe un sesgo sistemático y define los límites de concordancia clínica.",
    "Passing-Bablok": "Regresión lineal robusta utilizada para comparar dos métodos analíticos. No es sensible a valores atípicos y permite determinar si hay errores sistemáticos constantes (intercepto) o proporcionales (pendiente).",
    "Kaplan-Meier": "Estima la probabilidad de que los pacientes sobrevivan a lo largo del tiempo sin experimentar un evento (ej. muerte o recaída). Requiere datos de tiempo de seguimiento y el estado final (evento o censurado).",
    "Log-rank test": "Compara estadísticamente dos o más curvas de supervivencia de Kaplan-Meier. Úselo para evaluar si un tratamiento mejora el tiempo de supervivencia frente a un grupo control.",
    "Meta-analisis": "Sintetiza matemáticamente los resultados de múltiples estudios independientes. Úselo para obtener una estimación global y más potente del tamaño del efecto (ej. odds ratio global) de una intervención.",
    "Tamano muestral (1 media)": "Calcula cuántos pacientes necesita reclutar para demostrar que la media de su muestra difiere de un valor de referencia conocido, considerando la potencia y significancia deseadas.",
    "Tamano muestral (2 medias)": "Calcula la cantidad de pacientes necesarios para detectar una diferencia clínica importante entre dos grupos independientes. Es crucial para el diseño de ensayos clínicos.",
    "Tamano muestral (2 proporciones)": "Determina la muestra necesaria para comparar tasas de éxito o prevalencia entre dos grupos (ej. porcentaje de curación con droga A vs droga B).",
    "Poder estadistico": "Analiza retrospectivamente si un estudio que no encontró diferencias significativas tenía el tamaño muestral suficiente (potencia > 80%) para haberlas detectado si existieran.",
    "Bootstrap (media)": "Técnica de remuestreo computacional para calcular intervalos de confianza de la media. Excelente alternativa cuando los datos no cumplen los supuestos de normalidad tradicional.",
    "Bootstrap (diferencia)": "Calcula el intervalo de confianza para la diferencia de medias mediante remuestreo. Muy útil cuando se comparan grupos pequeños con distribuciones desconocidas o asimétricas.",
    "Bootstrap (correlacion)": "Estima la robustez de un coeficiente de correlación mediante remuestreo repetido, ideal cuando se sospecha que unos pocos puntos pueden estar influenciando excesivamente el resultado.",
    "Random Forest (clasificacion)": "Algoritmo de machine learning que utiliza múltiples árboles de decisión para clasificar pacientes en categorías (ej. alto riesgo / bajo riesgo) basado en múltiples variables predictoras complejas.",
    "Random Forest (regresion)": "Modelo predictivo avanzado que estima un valor numérico continuo usando múltiples árboles. Puede capturar interacciones complejas no lineales entre las variables del paciente.",
    "Mann-Whitney U": "Prueba no paramétrica equivalente al t-test independiente. Úsela para comparar dos grupos cuando los datos no son normales, son ordinales, o existen valores atípicos extremos.",
    "Wilcoxon pareado": "Prueba no paramétrica para muestras relacionadas (antes/después). Es la alternativa al t-test pareado cuando las diferencias no se distribuyen normalmente.",
    "Chi-cuadrado": "Prueba de asociación para dos variables categóricas (ej. grupo sanguíneo y presencia de enfermedad). Requiere que las frecuencias esperadas en la tabla de contingencia sean suficientes (>5).",
    "Fisher exact": "Alternativa exacta al Chi-cuadrado para tablas 2x2. Es indispensable cuando se tienen muestras muy pequeñas o frecuencias esperadas menores a 5 celdas.",
    "McNemar": "Analiza cambios en proporciones para datos pareados. Ideal para estudios antes-después donde el resultado es categórico (ej. positivo/negativo antes y después de tratamiento).",
    "Kruskal-Wallis": "El equivalente no paramétrico de ANOVA de una vía. Permite comparar las medianas de tres o más grupos independientes cuando no se puede asumir normalidad poblacional.",
    "Friedman": "Alternativa no paramétrica para ANOVA de medidas repetidas. Se usa cuando se evalúa a los mismos pacientes en 3 o más momentos distintos (ej. basal, mes 1, mes 6) sin asumir normalidad.",
    "F-test (varianzas)": "Compara las varianzas de dos poblaciones para determinar si son significativamente diferentes. Es útil para evaluar si dos métodos analíticos tienen la misma precisión.",
    "Kappa": "Evalúa el grado de concordancia entre dos observadores o métodos al clasificar datos categóricos (ej. dos patólogos leyendo biopsias), corrigiendo la coincidencia debida al azar.",
    "ICC": "Coeficiente de Correlación Intraclase. Mide la fiabilidad y concordancia de mediciones continuas realizadas por diferentes evaluadores o equipos sobre la misma muestra.",
    "Cronbach alfa": "Mide la consistencia interna o fiabilidad de un test o cuestionario compuesto por múltiples ítems (ej. escalas psicométricas de dolor o calidad de vida).",
    "Regresion lineal": "Modela matemáticamente cómo una variable numérica (dependiente) cambia en función de otra (independiente). Úselo para predecir valores o establecer tendencias de calibración.",
    "Regresion multiple": "Extensión de la regresión lineal que predice un resultado numérico usando múltiples variables independientes simultáneamente, controlando posibles factores de confusión.",
    "Regresion logistica": "Estima la probabilidad de que ocurra un evento binario (ej. mortalidad: sí/no) basándose en una o más variables predictoras clínicas (edad, sexo, biomarcadores).",
    "Odds Ratio": "Mide las probabilidades relativas de que ocurra un evento bajo cierta exposición frente a su ausencia. Es la medida estándar de asociación en estudios retrospectivos de casos y controles.",
    "Riesgo Relativo": "Calcula el riesgo de un evento en el grupo expuesto comparado con el grupo no expuesto. Aplicable en estudios prospectivos de cohortes o ensayos clínicos controlados.",
    "Diagnostic test": "Evalúa la utilidad clínica de una prueba. Requiere resultados de la prueba y el estándar de oro para calcular Sensibilidad, Especificidad y Valores Predictivos (VPP, VPN).",
    "Outliers (Grubbs)": "Detecta si el valor más extremo en un conjunto de datos es un valor atípico estadísticamente significativo. Asume que el resto de los datos se distribuye normalmente.",
    "Outliers (Tukey)": "Identifica valores atípicos utilizando rangos intercuartílicos (IQR). Es más robusto que Grubbs y no requiere que los datos sigan estrictamente una distribución normal.",
    "Intervalos de referencia": "Calcula los valores esperados para una población sana (generalmente percentiles 2.5 y 97.5). Indispensable para establecer rangos normales de laboratorio para nuevos analitos.",
    "Asimetria y curtosis": "Métricas que evalúan formalmente la forma de la distribución de los datos. Desviaciones significativas de 0 indican que los datos están sesgados (colas asimétricas) o son muy apuntados.",
    "Media recortada": "Calcula la media descartando un porcentaje (ej. 5%) de los valores más extremos superiores e inferiores. Proporciona un estimado robusto de la tendencia central resistente a outliers.",
    "Correlacion parcial": "Mide la relación lineal entre dos variables continuas mientras se elimina (controla) matemáticamente el efecto de una tercera variable de confusión.",
    "Media geometrica": "Medida de tendencia central adecuada para datos que crecen exponencialmente o están fuertemente sesgados a la derecha (ej. títulos de anticuerpos o cargas virales).",
    "Media armonica": "Promedio utilizado frecuentemente para analizar tasas y proporciones. Es útil cuando se trabaja con promedios de velocidades o tiempos de procesamiento de laboratorio.",
    "t-test 1 muestra": "Compara la media observada de su muestra frente a un valor teórico conocido o establecido previamente. Úselo para verificar si sus datos se desvían de un estándar.",
    "ANOVA una via (core)": "Prueba paramétrica para comparar medias de múltiples grupos. Usado como motor de cálculo interno optimizado para reportes de comparaciones múltiples.",
    "Sign test": "Alternativa muy simple al Wilcoxon pareado que solo evalúa la dirección del cambio (positivo o negativo) sin considerar la magnitud. Es extremadamente robusto a outliers.",
    "Cochran Q": "Extensión de la prueba de McNemar para comparar 3 o más tratamientos en datos dicotómicos relacionados (ej. éxito/fracaso de 3 terapias diferentes en los mismos pacientes).",
    "Kappa ponderado": "Versión del índice Kappa que penaliza los desacuerdos entre evaluadores dependiendo de su magnitud. Esencial para categorías ordinales (ej. grados tumorales I, II, III).",
    "Deming regression": "Regresión lineal avanzada que asume que existen errores de medición tanto en X como en Y. Es el método recomendado (junto con Passing-Bablok) para comparar métodos de laboratorio.",
    "CV duplicatas": "Calcula el Coeficiente de Variación analítico a partir de muestras procesadas en duplicado. Es clave para validar la repetibilidad intralaboratorio de un ensayo.",
    "Likelihood Ratios": "Razones de verosimilitud (LR+ y LR-) que indican cuánto cambia la probabilidad post-prueba de una enfermedad. LR+ alto (>10) confirma; LR- bajo (<0.1) descarta firmemente.",
    "Comparar 2 medias": "Calcula diferencias significativas entre dos grupos ingresando directamente datos resumidos (media, DE, n) sin necesidad de tener los datos crudos originales.",
    "Comparar 2 proporciones": "Evalúa diferencias entre tasas de éxito utilizando datos agrupados (casos/totales) en lugar de variables binarias individuales a nivel de paciente.",
    "Comparar 2 AUC": "Prueba estadística formal (ej. método DeLong) para determinar si un biomarcador es significativamente mejor que otro al comparar las áreas bajo sus curvas ROC.",
    "Tabla de percentiles": "Genera una tabla completa de cuantiles (ej. p5, p10, p50, p90, p95) con sus respectivos intervalos de confianza. Útil para curvas de crecimiento pediátrico.",
    "Edad-relacionada": "Permite segmentar y calcular intervalos de referencia específicos para distintos grupos etarios o factores continuos. Clave en analitos como hormonas pediátricas.",
    "Outliers (ESD)": "Prueba de Desviación Estudentizada Extrema Generalizada (Rosner). Detecta progresivamente múltiples outliers simultáneos en una serie, superando el límite de Grubbs.",
    "Bootstrap (mediana)": "Remuestreo para calcular el intervalo de confianza de la mediana. Extremadamente útil en datos fuertemente asimétricos como tiempos de hospitalización.",
    "Bootstrap (regresion)": "Genera estimaciones robustas e intervalos empíricos para las pendientes de regresión. Se emplea cuando se violan los supuestos de homocedasticidad o normalidad de los residuos.",
    "Tamaño muestral (correlacion)": "Determina el número de sujetos necesarios para detectar si un coeficiente de correlación específico es estadísticamente diferente de cero.",
    "ANOVA dos vias": "Analiza simultáneamente el efecto de dos variables categóricas independientes sobre una respuesta continua. También evalúa si existe interacción entre los factores.",
    "ANCOVA": "Análisis de covarianza. Compara grupos ajustando por variables continuas de confusión (covariables, ej. edad basal). Aumenta el poder estadístico al reducir el error residual.",
    "Medidas repetidas": "Compara promedios de la misma variable medida en múltiples ocasiones en los mismos sujetos. Aplica correcciones automáticas (Greenhouse-Geisser) para violaciones de esfericidad.",
    "Cox regression": "Modelo de riesgos proporcionales. Estima cómo múltiples factores de riesgo influyen simultáneamente en el tiempo de supervivencia de los pacientes frente a un evento clínico.",
    "Probit regression": "Modelo predictivo para respuestas binomiales basado en la distribución normal acumulada. Utilizado frecuentemente en toxicología y farmacología (ej. análisis dosis-respuesta y LD50).",
    "CMH test": "Test de Cochran-Mantel-Haenszel. Permite analizar la asociación en tablas de contingencia 2x2 controlando (estratificando) por una tercera variable de confusión multicategórica.",
    "Mediciones seriales": "Resumen longitudinal de mediciones en pacientes (ej. curvas de glucosa). Permite calcular y analizar métricas como el Área Bajo la Curva (AUC), Cmax o Tmax individual.",
    "Youden plot": "Representación gráfica avanzada de la sensibilidad frente a la especificidad. Ayuda a seleccionar visualmente el punto de corte óptimo que maximiza el Índice de Youden.",
    "Polar plot": "Gráfico de radar utilizado para visualizar y comparar simultáneamente múltiples parámetros (ej. panel de citocinas) entre grupos o estados de la enfermedad.",
    "Waterfall chart": "Visualiza los cambios secuenciales positivos y negativos frente a un valor basal. Frecuentemente usado en oncología para mostrar la reducción o progresión del tamaño tumoral en pacientes.",
    "Mountain plot": "También conocido como gráfico de distribución plegada (folded empirical CDF). Muestra de forma muy sensible las diferencias de distribución o sesgos entre dos métodos clínicos.",
    "Bland-Altman múltiple": "Adaptación del método de Bland-Altman para cuando se tienen mediciones repetidas en los mismos sujetos para ambos métodos. Considera la varianza intra-sujeto e inter-sujeto.",
}
